# Generated by Django 4.2 on 2023-05-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0005_room_reservation_room_number_reservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatspace', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
