# Generated by Django 4.2 on 2023-05-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0009_alter_chat_chatspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chatspace',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
